version: 2.1

var_1: &docker_image circleci/node:10.13.0-browsers
var_2: &sdk_cache_key raiden-{{ .Branch }}-{{ checksum "package-lock.json" }}
var_3: &dapp_cache_key raiden-dapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
var_4: &raiden_working_dir ~/src/raiden
var_5: &dapp_working_dir ~/src/raiden-dapp

anchor_1: &sdk_package_lock_key
  key: *sdk_cache_key

anchor_2: &attach_options
  at: ~/src/
  
anchor_3: &dapp_package_lock_key
  key: *dapp_cache_key

executors:
  base-executor:
    working_directory: ~/src
    docker:
      - image: *docker_image

jobs:
  checkout: 
    executor: base-executor
    working_directory: ~/src
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  install_sdk:
    executor: base-executor
    working_directory: *raiden_working_dir
    steps:
      - attach_workspace: *attach_options
      - restore_cache: *sdk_package_lock_key
      - run: npm install
      - save_cache:
          <<: *sdk_package_lock_key
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: ~/src
          paths:
            - ./*

  install_dapp:
    executor: base-executor
    working_directory: *dapp_working_dir
    steps:
      - attach_workspace: *attach_options
      - restore_cache: *dapp_package_lock_key
      - run: npm install
      - save_cache:
          <<: *dapp_package_lock_key
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: ~/src
          paths:
            - ./*

  lint_sdk:
    executor: base-executor
    working_directory: *raiden_working_dir
    steps:
      - attach_workspace: *attach_options
      - run: npm run lint

  lint_dapp:
    executor: base-executor
    working_directory: *dapp_working_dir
    steps:
    - attach_workspace: *attach_options
    - run: npm run lint:check

  test_sdk:
    executor: base-executor
    working_directory: *raiden_working_dir
    steps:
      - attach_workspace: *attach_options    
      - run: 
          name: Run unit tests
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
           path: reports/junit
      - store_artifacts:
           path: reports/junit
      - run:
          name: "Upload coverage"
          command: cd .. && bash <(curl -s https://codecov.io/bash)  -F sdk 

  test_dapp:
    executor: base-executor
    working_directory: *dapp_working_dir
    steps:
      - attach_workspace: *attach_options
      - run: 
          name: Run unit tests
          command: npm run test:unit -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
           path: reports/junit
      - store_artifacts:
           path: reports/junit
      - run:
          name: "Upload coverage"
          command: cd .. && bash <(curl -s https://codecov.io/bash) -F dapp 

  build_sdk:
    executor: base-executor
    working_directory: *raiden_working_dir
    steps:
      - attach_workspace: *attach_options
      - run: npm run build

  build_dapp:
    executor: base-executor
    working_directory: *dapp_working_dir
    steps:
      - attach_workspace: *attach_options
      - run: npm run build
      - persist_to_workspace:
          root: ~/src
          paths:
            - ./*

workflows:
  version: 2
  default_workflow:
    jobs:
      - checkout
      - install_sdk:
          requires:
            - checkout
      - install_dapp:
          requires:
            - checkout
      - lint_sdk:
          requires:
            - install_sdk
      - lint_dapp:
          requires:
            - install_dapp
      - build_sdk:
          requires:
            - install_sdk
      - build_dapp:
          requires:
            - install_dapp
      - test_sdk:
          requires:
            - lint_sdk
            - build_sdk
      - test_dapp:
          requires:
            - lint_dapp
            - build_dapp
          
