version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/raiden-ts"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    commit_message:
      prefix: "dependencies"

  - package_manager: "javascript"
    directory: "/raiden-dapp"
    update_schedule: "weekly"
    default_labels:
      - "dependencies"
    commit_message:
      prefix: "dependencies"
